import sm1 from './sm1.png'
import sm2 from './sm2.png'
import sm3 from './sm3.png'
import sm4 from './sm4.png'
import sm5 from './sm5.png'
import sm6 from './sm6.png'
import sm7 from './sm7.png'
import sm8 from './sm8.png'
import sm9 from './sm9.png'
import sm10 from './sm10.png'
import sm11 from './sm11.png'
import sm12 from './sm12.png'
import sm13 from './sm13.png'
import U from './U.png'
import window from './window.jpg'
import panz from './panz.png'
import mus from './mus.png'
export{sm1,sm2,sm3,sm4,sm5,sm6,sm7,sm8,sm9,sm10,sm11,sm12,sm13,U,window,panz,mus};